### ISSUE TITLE
 Packet ignored. Broken data was received

### ISSUE THREAD

**Issue by Hexon-Boi** [sqproxy/sqproxy#124]
![ASS](https://github.com/sqproxy/sqproxy/assets/70663961/3813ec6d-2d5a-45ea-9419-c3adf4c02ed4)
![asdasd](https://github.com/sqproxy/sqproxy/assets/70663961/580bc917-9f92-4152-9df5-75cbf3fdb11a)

```yaml
# Defaults for each server in `servers` section
# Any of these `values` can be overridden locally:
# in local `defaults` section
# in `servers` section
defaults:
  # True - defaults will be applied for each NEXT config file in conf.d directory
  # False - applied only for current file
  # conf.d/ files read sequentially by alphabetical order
  # we recommend start config names with sequential value: 00-globals.yaml, 01-game1.yaml, 02-game2.yaml
  __global__: True
  network:
    # Real game server IP address
    server_ip: '135.xxx.xxx.xxx'
    # IP address for listening incoming queries
    # by default is equal to server_ip, can be omitted (null) or equal to '0.0.0.0'
    bind_ip: null
    # Real game server PORT (respect to server_ip)
    server_port: 0  # don't set in globals, only for doc here
    # PORT for listening incoming queries (respect to bind_ip)
    # by default first available port will be used
    # can be omitted (null) or specified; zero (0) is equal to first available port
    bind_port: 0
    # False (default) - queries from `server_port` will be redirected to `bind_port`
    # only for auto-ebpf handling, for more info see `ebpf` section below
    # True - disable redirection (useful for just proxying and debug purposes)
    ebpf_no_redirect: false

  # Some games have integrated ddos protection
  # and can ban source ip:port for often queries
  # To prevent banning increase cache lifetime(s)

  # How often update A2S_INFO data
  a2s_info_cache_lifetime: 5
  # How often update A2S_RULES data
  a2s_rules_cache_lifetime: 5
  # How often update A2S_PLAYERS data
  a2s_players_cache_lifetime: 1

  # How long wait a2s response
  # can be superseded by a2s_*_cache_lifetime option
  # cause we choose max(a2s_response_timeout, a2s_*_cache_lifetime)
  # This option protect you in situation
  # when server respond longer than your a2s_*_cache_lifetime
  a2s_response_timeout: 1

  # False (default) - no action, A2S_RULES will work
  # True - don't update A2S_RULES cache
  # This will be helpful for HLDS servers which protocol is different
  # But be careful, you also need disable redirection for A2S_RULES packets
  # see the IS_QUERY_REQUEST_PACKET in https://github.com/spumer/source-query-proxy-kernel-module/blob/master/src-ebpf/utils.h
  # CS:GO also has broken A2S_RULES, but fix available at https://forums.alliedmods.net/showthread.php?t=236521
  no_a2s_rules: false


# servers sections is required and can't be empty
# it can be filled by other .yaml files
# See 01-dummy-game.yaml
servers:
  gmodserver:
    network:
      server_port: 27015

# Automatically run eBPF redirection
ebpf:
  # Install any release of SQRedirect
  # https://github.com/sqproxy/sqredirect/releases
  # If you want run it without root privileges, see: https://github.com/sqproxy/sqredirect#non-root-running
  # and make sure executable prepended with 'sudo':
  #   executable:
  #     - 'sudo'
  #     - 'sqredirect'
  enabled: True
  executable: 'sqredirect'
  ```
