### ISSUE TITLE
[Question]How to configure sqproxy for a NAT server

### ISSUE THREAD

**Issue by fantasylidong** [sqproxy/sqproxy#132]
If I have a NAT machine running four Left 4 Dead 2 game instances, with the ports 1111, 1112, 1113, and 1114 assigned to them, and four additional idle ports 1115, 1116, 1117, and 1118, the public IP is 123.123.123.123, and the internal IP is 172.17.1.31, how should I configure the sqproxy configuration file? The public IP is not bound to the host, communication is conducted through the internal IP, and the host can be accessed using the public IP + port.

PS: NAT server means many server use one ip. Only few port can access your own server and your own server have only internal IP.

ChatGPT give me a configuration but didn't work.
```
defaults:
  __global__: True
  network:
    server_ip: '172.17.1.31'
    bind_ip: '0.0.0.0'
    ebpf_no_redirect: false

servers:
  anne:
    network:
      server_port: 1111   
      bind_port: 1111     
  anne2:
    network:
      server_port: 1112
      bind_port: 1112
  anne3:
    network:
      server_port: 1113
      bind_port: 1113
  anne4:
    network:
      server_port: 1114
      bind_port: 1114

ebpf:
  enabled: false
  executable: 'sqredirect'
```
It didn't work, bind ip and port is ok, but sqproxy didn't check server up.

**Comment by spumer** [comment]
NAT does not matter.

If you run sqproxy on the same machine you should use different bind_port (!= server_port)

![same host](https://github.com/user-attachments/assets/dad54b30-6d5c-48f9-a831-853c8eef568e)

```yaml
defaults:
  __global__: True
  network:
    server_ip: '172.17.1.31'

  # recommended lifetime options for L4D2
  a2s_info_cache_lifetime: 10
  a2s_rules_cache_lifetime: 10
  a2s_players_cache_lifetime: 2

servers:
  anne:
    network:
      server_port: 1111   
  anne2:
    network:
      server_port: 1112
  anne3:
    network:
      server_port: 1113
  anne4:
    network:
      server_port: 1114

ebpf:
  enabled: true
  executable: 'sqredirect'
```

Here bind_port omitted and will be choosen automatically by sqproxy. Auto-splitted traffic will be redirected to choosen port.

**Comment by spumer** [comment]
If you want run sqproxy on **different host** - it's possible and config will be same. But you should manually redirect other traffic for this case, e.g via iptables

**Comment by fantasylidong** [comment]
Thanks for good decription image.
I think I now understand how to configure a server behind NAT. Here's an example configuration:
```
defaults:
  __global__: True
  network:
   #internal IP
    server_ip: '172.17.1.31'
    bind_ip: '172.17.1.31'
    server_port: 0
    bind_port: 0
    ebpf_no_redirect: false

  a2s_info_cache_lifetime: 10
  a2s_rules_cache_lifetime: 10
  a2s_players_cache_lifetime: 2
  a2s_response_timeout: 1
  no_a2s_rules: true
  wait_ready_graceful_period: 30
  max_a2s_fails_before_offline: 10

#one server need two ports which can access the server
servers:
  anne:
    network:
      server_port: 1326
      bind_port: 6425
  anne2:
    network:
      server_port: 2970
      bind_port: 2186
  anne3:
    network:
      server_port: 3877
      bind_port: 3504
  anne4:
    network:
      server_port: 8712
      bind_port: 1596

ebpf:
  enabled: true
  executable: 'sqredirect'
```

I tested the configuration, and it works correctly now.

**Comment by spumer** [comment]
I recommend you set lifetime options like this
```
  # recommended lifetime options for L4D2
  a2s_info_cache_lifetime: 10
  a2s_rules_cache_lifetime: 10
  a2s_players_cache_lifetime: 2
```
This tested over years by me

**Comment by fantasylidong** [comment]
Can i only use one a2s cacher like this?
```
defaults:
  __global__: True
  network:
    server_ip: '172.16.0.38'
    bind_ip: '172.16.0.38'
    server_port: 0
    bind_port: 0
    ebpf_no_redirect: false
  a2s_info_cache_lifetime: 10
  a2s_rules_cache_lifetime: 10
  a2s_players_cache_lifetime: 2
  a2s_response_timeout: 1
  no_a2s_rules: true
  wait_ready_graceful_period: 30
  max_a2s_fails_before_offline: 10
servers:
  anne1:
    network:
      server_port: 21221
      bind_port: 21220
  anne2:
    network:
      server_port: 21222
      bind_port: 21220
  anne3:
    network:
      server_port: 21223
      bind_port: 21220
  anne4:
    network:
      server_port: 21224
      bind_port: 21220
  anne5:
    network:
      server_port: 21225
      bind_port: 21220
  anne6:
    network:
      server_port: 21226
      bind_port: 21220
  anne7:
    network:
      server_port: 21227
      bind_port: 21220
  anne8:
    network:
      server_port: 21228
      bind_port: 21220
ebpf:
  enabled: true
  executable: 'sqredirect'
```
